version: '3'
services:
  web:
    build: .
    ports:
     - "8989:8080"
    depends_on:
     - minio
  minio:
    image: minio/minio:RELEASE.2018-10-18T00-28-58Z
    hostname: minio
    volumes:
     - data1:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    ports:
     - "9000:9000"

volumes:
  data1:
